import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Chakra} from "@/app/chakra";
import {StoreProvider} from "@/src/stores/storeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        <StoreProvider>
            <Chakra>
                {children}
            </Chakra>
        </StoreProvider>
        </body>
        </html>
    );
}